### ISSUE TITLE
.toLowerCase() and .map are undefined

### ISSUE THREAD

**Issue by DeathCookieOP** [Jake-Ruston/fortnite#13]
In the src/user.js .toLowerCase() was undefined, so I tried to remove that... but then .map was also undefined, so i tried to remove that but then the rest of it was then not a function.... help?

https://gyazo.com/54ac47cc435eee9de77c11305074b570
ERROR: https://gyazo.com/31d43a56e06e7d0d9f7213f7b9aba750

**Comment by TheAlgerianPrince** [comment]
same for me

**Comment by DemonFromHeaven** [comment]
it seems like the user(username, platform) function doesnt go through the async function defined in the Cleint.js

**Comment by ditpowuh** [comment]
I am currently having the same issue as well.

**Comment by DjordyKoert** [comment]
i have the same problem

**Comment by Kdodd1** [comment]
Did anyone figure this out yet? I'm getting the same thing

**Comment by Kdodd1** [comment]
You're a saint. Thanks I appreciate that!

**Comment by RyanGamingXbox** [comment]
Thanks for that
