### ISSUE TITLE
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by TutoRapide** [Jake-Ruston/fortnite#17]
I have this mistake as long as there are unknown characters 
example with this perso 最終学歴ホイ卒4歳子持ち無職DT

**Comment by Jake-Ruston** [comment]
@TutoRapide Sorry about that, I have now fixed that error in a new version. Update with `npm up / yarn upgrade`.

**Comment by TutoRapide** [comment]
thank
