### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by 123Drew123** [Jake-Ruston/fortnite#9]
getting 403 forbidden when trying to get info from api

**Comment by Jake-Ruston** [comment]
@123Drew123 Hi Drew, I have noticed this myself too. I think FortniteTracker's API is down or something like that, their contact page is also unavailable (https://fortnitetracker.com/contact) so I am unable to contact them at the moment, sorry about this

**Comment by 123Drew123** [comment]
Alright thanks for the quick response I’ll try again in a bit

**Comment by Jake-Ruston** [comment]
@123Drew123 So I've been informed that the API is fully functioning and if you are still getting this 403 error after this rewrite (`npm update fortnite`!) then you need to contact FortniteTracker's site owners.
